name: Build, test and lint affected packages

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'next', 'canary']

# Cancel any previous runs in progress
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v4

      - run: npm ci

      - run: npx nx format:check
      - run: npx nx affected -t lint,test,build --parallel=3 --exclude='*,!tag:package'
